CREATE TABLE `landing_page_config` (
	`id` int NOT NULL DEFAULT 1,
	`heroHeadline` varchar(255) NOT NULL DEFAULT 'Faça seu bolão com a galera',
	`heroSubheadline` text,
	`heroBadgeText` varchar(128) NOT NULL DEFAULT 'FAÇA SEU BOLÃO PARA A COPA DO MUNDO',
	`heroBadgeEnabled` boolean NOT NULL DEFAULT true,
	`heroCountdownEnabled` boolean NOT NULL DEFAULT true,
	`heroCountdownDate` varchar(32) NOT NULL DEFAULT '2026-06-11T16:00:00Z',
	`heroCtaPrimaryText` varchar(64) NOT NULL DEFAULT 'Criar bolão grátis',
	`heroCtaSecondaryText` varchar(64) NOT NULL DEFAULT 'Quero campeonato personalizado → Pro',
	`heroCtaSecondaryEnabled` boolean NOT NULL DEFAULT true,
	`sectionCredibilityEnabled` boolean NOT NULL DEFAULT true,
	`sectionHowItWorksEnabled` boolean NOT NULL DEFAULT true,
	`sectionDifferentialEnabled` boolean NOT NULL DEFAULT true,
	`sectionFeaturesEnabled` boolean NOT NULL DEFAULT true,
	`sectionPlansEnabled` boolean NOT NULL DEFAULT true,
	`sectionFaqEnabled` boolean NOT NULL DEFAULT true,
	`sectionCtaFinalEnabled` boolean NOT NULL DEFAULT true,
	`differentialHeadline` varchar(255) NOT NULL DEFAULT 'Seu campeonato. Suas regras.',
	`differentialBody` text,
	`ctaFinalHeadline` varchar(255) NOT NULL DEFAULT 'A Copa do Mundo 2026 começa em junho. O seu bolão pode começar hoje.',
	`ctaFinalPrimaryText` varchar(64) NOT NULL DEFAULT 'Criar bolão grátis',
	`ctaFinalSecondaryText` varchar(64) NOT NULL DEFAULT 'Criar campeonato personalizado',
	`ctaFinalSecondaryEnabled` boolean NOT NULL DEFAULT true,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `landing_page_config_id` PRIMARY KEY(`id`)
);
